# ==========================================
# APPLICATION
# ==========================================

spring.application.name=skylink

server.port=8080


# ==========================================
# ACTIVE PROFILE
# ==========================================

spring.profiles.active=linux


# ==========================================
# H2 DATABASE
# ==========================================

spring.datasource.url=jdbc:h2:file:./data/skylink
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# H2 CONSOLE
# ==========================================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ==========================================
# ACTUATOR
# ==========================================

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=when_authorized


# ==========================================
# LOGGING
# ==========================================

logging.level.root=INFO
logging.level.com.example.skylink=INFO